// Types for our data
export interface Recipe {
  id: number
  title: string
  description: string
  image: string
  cuisine: string
  dietaryRestrictions: string[]
  prepTime: number
  cookTime: number
  ingredients: string[]
  instructions: string[]
}

// Available cuisine types and dietary restrictions
export const cuisineTypes = ["All", "Italian", "Indian", "Mexican", "Greek", "Chinese", "Thai", "International"]
export const dietaryOptions = ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"]

// Mock data for recipes
export const recipesData: Recipe[] = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    description: "A classic Italian pasta dish with eggs, cheese and pancetta",
    image: "https://placehold.co/400x300/e63946/ffffff?text=Spaghetti+Carbonara",
    cuisine: "Italian",
    dietaryRestrictions: [],
    prepTime: 15,
    cookTime: 20,
    ingredients: [
      "400g spaghetti",
      "150g pancetta",
      "2 large eggs",
      "50g pecorino cheese",
      "50g parmesan cheese",
      "Black pepper",
      "Salt",
    ],
    instructions: [
      "Cook pasta in salted boiling water according to package instructions.",
      "While pasta cooks, fry diced pancetta in a large pan until crispy.",
      "In a bowl, whisk eggs and grated cheeses together with freshly ground black pepper.",
      "Drain pasta, reserving a cup of pasta water.",
      "Working quickly, add hot pasta to the pancetta pan, remove from heat.",
      "Pour in egg and cheese mixture, tossing rapidly to create a creamy sauce.",
      "Add a splash of pasta water if needed to loosen the sauce.",
      "Serve immediately with extra cheese and black pepper.",
    ],
  },
  {
    id: 2,
    title: "Vegetable Curry",
    description: "A flavorful vegetarian curry with mixed vegetables and Indian spices",
    image: "https://placehold.co/400x300/e9c46a/000000?text=Vegetable+Curry",
    cuisine: "Indian",
    dietaryRestrictions: ["Vegetarian", "Gluten-Free"],
    prepTime: 20,
    cookTime: 30,
    ingredients: [
      "2 cups mixed vegetables (carrots, peas, potatoes, cauliflower)",
      "1 onion, finely chopped",
      "2 cloves garlic, minced",
      "1-inch piece ginger, grated",
      "2 tbsp curry paste",
      "1 can coconut milk",
      "1 cup vegetable broth",
      "Fresh coriander",
      "Basmati rice to serve",
    ],
    instructions: [
      "Heat oil in a large pot over medium heat.",
      "Add onions and cook until translucent, about 5 minutes.",
      "Add garlic and ginger, cook for another minute until fragrant.",
      "Stir in curry paste and cook for 2 minutes.",
      "Add chopped vegetables and stir to coat with the spices.",
      "Pour in coconut milk and vegetable broth, bring to a simmer.",
      "Cover and cook for 20-25 minutes until vegetables are tender.",
      "Garnish with fresh coriander and serve with basmati rice.",
    ],
  },
  {
    id: 3,
    title: "Vegan Tacos",
    description: "Plant-based tacos with roasted cauliflower and spicy sauce",
    image: "https://placehold.co/400x300/2a9d8f/ffffff?text=Vegan+Tacos",
    cuisine: "Mexican",
    dietaryRestrictions: ["Vegan", "Dairy-Free"],
    prepTime: 25,
    cookTime: 15,
    ingredients: [
      "1 head cauliflower, cut into florets",
      "2 tbsp olive oil",
      "2 tsp taco seasoning",
      "1 can black beans, drained and rinsed",
      "8 corn tortillas",
      "1 avocado, sliced",
      "1 lime, cut into wedges",
      "Fresh cilantro",
      "Hot sauce to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Toss cauliflower florets with olive oil and taco seasoning.",
      "Spread on a baking sheet and roast for 20-25 minutes until golden and tender.",
      "Warm black beans in a small saucepan over medium heat.",
      "Heat tortillas according to package instructions.",
      "Assemble tacos with roasted cauliflower, black beans, and avocado slices.",
      "Garnish with cilantro, a squeeze of lime, and hot sauce.",
    ],
  },
  {
    id: 4,
    title: "Greek Salad",
    description: "Fresh Mediterranean salad with feta cheese and olives",
    image: "https://placehold.co/400x300/457b9d/ffffff?text=Greek+Salad",
    cuisine: "Greek",
    dietaryRestrictions: ["Vegetarian", "Gluten-Free"],
    prepTime: 15,
    cookTime: 0,
    ingredients: [
      "1 cucumber, diced",
      "4 large tomatoes, cut into chunks",
      "1 red onion, thinly sliced",
      "1 green bell pepper, chopped",
      "200g feta cheese, cubed",
      "1/2 cup kalamata olives",
      "3 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Combine cucumber, tomatoes, red onion, and bell pepper in a large bowl.",
      "Add olives and feta cheese.",
      "In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.",
      "Pour dressing over the salad and toss gently to combine.",
      "Let sit for 10 minutes before serving to allow flavors to meld.",
    ],
  },
  {
    id: 5,
    title: "Beef and Broccoli",
    description: "Classic Chinese stir-fry with tender beef and crunchy broccoli",
    image: "https://placehold.co/400x300/d62828/ffffff?text=Beef+and+Broccoli",
    cuisine: "Chinese",
    dietaryRestrictions: ["Dairy-Free"],
    prepTime: 20,
    cookTime: 15,
    ingredients: [
      "500g beef strips",
      "2 cups broccoli florets",
      "3 cloves garlic, minced",
      "1-inch piece ginger, grated",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "1 tsp sesame oil",
      "Steamed rice to serve",
    ],
    instructions: [
      "Marinate beef strips in 1 tbsp soy sauce and cornstarch for 15 minutes.",
      "Blanch broccoli in boiling water for 2 minutes, then drain and rinse with cold water.",
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add beef and stir-fry until browned, about 3-4 minutes. Remove and set aside.",
      "In the same pan, add garlic and ginger, stir-fry for 30 seconds until fragrant.",
      "Add broccoli and stir-fry for 2 minutes.",
      "Return beef to the pan, add remaining soy sauce and oyster sauce.",
      "Stir-fry for another 2 minutes until everything is well coated and heated through.",
      "Drizzle with sesame oil and serve with steamed rice.",
    ],
  },
  {
    id: 6,
    title: "Mushroom Risotto",
    description: "Creamy Italian rice dish with mushrooms and parmesan",
    image: "https://placehold.co/400x300/6d6875/ffffff?text=Mushroom+Risotto",
    cuisine: "Italian",
    dietaryRestrictions: ["Vegetarian", "Gluten-Free"],
    prepTime: 15,
    cookTime: 30,
    ingredients: [
      "1.5 cups arborio rice",
      "300g mixed mushrooms, sliced",
      "1 onion, finely diced",
      "2 cloves garlic, minced",
      "1/2 cup dry white wine",
      "4 cups vegetable stock, kept warm",
      "1/2 cup grated parmesan cheese",
      "2 tbsp butter",
      "2 tbsp olive oil",
      "Fresh thyme leaves",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a large pan over medium heat.",
      "Add mushrooms and cook until golden, about 5 minutes. Remove and set aside.",
      "In the same pan, add butter and sauté onion until translucent.",
      "Add garlic and cook for another minute.",
      "Add arborio rice and stir to coat with butter, cooking for 1-2 minutes until slightly translucent.",
      "Pour in white wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring constantly and waiting until each addition is absorbed before adding more.",
      "Continue this process for about 18-20 minutes until rice is creamy and al dente.",
      "Stir in cooked mushrooms, parmesan cheese, and thyme leaves.",
      "Season with salt and pepper, and serve immediately.",
    ],
  },
  {
    id: 7,
    title: "Chicken Pad Thai",
    description: "Popular Thai noodle dish with chicken, peanuts and lime",
    image: "https://placehold.co/400x300/fb8500/ffffff?text=Chicken+Pad+Thai",
    cuisine: "Thai",
    dietaryRestrictions: ["Dairy-Free"],
    prepTime: 25,
    cookTime: 15,
    ingredients: [
      "200g rice noodles",
      "300g chicken breast, sliced",
      "2 eggs, lightly beaten",
      "2 cups bean sprouts",
      "4 green onions, chopped",
      "1/4 cup roasted peanuts, chopped",
      "2 tbsp vegetable oil",
      "3 tbsp fish sauce",
      "2 tbsp tamarind paste",
      "2 tbsp brown sugar",
      "1 lime, cut into wedges",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Soak rice noodles in warm water for 15-20 minutes until softened, then drain.",
      "Mix fish sauce, tamarind paste, and brown sugar in a small bowl to make the sauce.",
      "Heat oil in a large wok or skillet over high heat.",
      "Add chicken and stir-fry until cooked through, about 5-6 minutes.",
      "Push chicken to one side, add beaten eggs to the empty side.",
      "Scramble eggs until set, then mix with the chicken.",
      "Add drained noodles and sauce to the wok, toss to combine.",
      "Stir in bean sprouts and half the green onions, cook for 2-3 minutes until noodles are tender.",
      "Remove from heat, garnish with remaining green onions, chopped peanuts, and cilantro.",
      "Serve with lime wedges on the side.",
    ],
  },
  {
    id: 8,
    title: "Vegan Buddha Bowl",
    description: "Nutritious bowl with grains, vegetables and tahini dressing",
    image: "https://placehold.co/400x300/606c38/ffffff?text=Vegan+Buddha+Bowl",
    cuisine: "International",
    dietaryRestrictions: ["Vegan", "Gluten-Free", "Dairy-Free"],
    prepTime: 20,
    cookTime: 30,
    ingredients: [
      "1 cup quinoa",
      "1 sweet potato, diced",
      "1 can chickpeas, drained and rinsed",
      "2 cups kale, chopped",
      "1 avocado, sliced",
      "1 tbsp olive oil",
      "1 tsp cumin",
      "1 tsp paprika",
      "2 tbsp tahini",
      "1 tbsp lemon juice",
      "1 tbsp maple syrup",
      "2 tbsp water",
      "Salt and pepper to taste",
      "2 tbsp sesame seeds",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Rinse quinoa and cook according to package instructions.",
      "Toss sweet potato cubes and chickpeas with olive oil, cumin, paprika, salt, and pepper.",
      "Spread on a baking sheet and roast for 25-30 minutes until tender and golden.",
      "Massage kale with a little olive oil and salt until softened.",
      "Make dressing by whisking together tahini, lemon juice, maple syrup, water, and a pinch of salt.",
      "Assemble bowls with quinoa as the base, then arrange roasted sweet potatoes, chickpeas, kale, and avocado slices.",
      "Drizzle with tahini dressing and sprinkle with sesame seeds.",
    ],
  },
]

